export interface User {
    id: number;
    name: string;
    email: string;
    email_verified_at: string;
}

export type PageProps<
    T extends Record<string, unknown> = Record<string, unknown>
> = T & {
    auth: {
        user: User;
    };
};

/// Generated by https://quicktype.io

export interface Exam {
    id: number;
    uuid: null;
    title: string;
    instructions: string;
    starts_at: string;
    ends_at: string;
    created_at: string;
    updated_at: string;
    questions: Question[];
}

export interface Question {
    id: number;
    question: string;
    options: string[];
    answer: string;
    exam_id: number;
    created_at: string;
    updated_at: string;
}

export interface Candidate {
    id: number;
    name: string;
    email: string;
    roll_no: string;
    password: string;
    created_at: null;
    updated_at: null;
}

// Generated by https://quicktype.io

export interface QuestionAttempt {
    id: number;
    attempt_id: number;
    question_id: number;
    answer: null | string;
    result: null;
    created_at: string;
    updated_at: string;
    question: Question;
}

// Generated by https://quicktype.io

export interface Attempt {
    id: number;
    candidate_id: number;
    exam_id: number;
    score: number;
    created_at: string;
    updated_at: string;
}
